name: Limux
description: Application de recommandation de films et séries

# Version publiée dans les stores
publish_to: 'none'

# Version de l'application
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^4.0.4
  
  # État
  provider: ^6.0.5
  
  # Stockage local et sécurité
  shared_preferences: ^2.1.1
  path_provider: ^2.0.15
  flutter_secure_storage: ^8.0.0
  encrypt: ^5.0.1
  crypto: ^3.0.3
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_analytics: ^10.7.4
  
  # Réseau et API
  http: ^0.13.6
  dio: ^5.1.2
  dio_http2_adapter: ^2.1.0
  http_certificate_pinning: ^2.0.0
  
  # Validation de formulaire
  form_field_validator: ^1.1.0
  email_validator: ^2.1.17
  
  # Utilitaires
  intl: ^0.18.1
  url_launcher: ^6.1.11
  share_plus: ^7.0.1
  image_picker: ^0.8.7+5
  uuid: ^3.0.7
  logger: ^1.3.0
  
  # Détection d'appareils rootés
  flutter_jailbreak_detection: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.4
  flutter_launcher_icons: ^0.14.3
  
  # Analyses de sécurité
  dart_code_metrics: ^5.7.2

# Configuration des icônes
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

# Configuration Flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/